"""init

Revision ID: c28e41cad3b0
Revises: 
Create Date: 2026-08-23 02:40:10.961214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c28e41cad3b0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gifts',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('mrp', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('rating', sa.String(length=10), nullable=False),
    sa.Column('reviews', sa.String(length=20), nullable=False),
    sa.Column('tag', sa.String(length=40), nullable=True),
    sa.Column('icon_key', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drops',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('share_code', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('theme_key', sa.String(length=20), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('selected_gift_id', sa.String(length=40), nullable=True),
    sa.Column('created_by_email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['selected_gift_id'], ['gifts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drops_share_code'), 'drops', ['share_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_drops_share_code'), table_name='drops')
    op.drop_table('drops')
    op.drop_table('gifts')
    # ### end Alembic commands ###
